# 运维堡垒机系统配置文件 - Docker生产环境
app:
  name: "bastion"
  version: "1.0.0"
  mode: "release"
  port: 8080
  host: "0.0.0.0"

# 数据库配置 - 使用Docker网络内部地址
database:
  type: "mysql"
  host: "172.20.0.7"  # MySQL容器的固定IP
  port: 3306
  username: "root"
  password: "password123"
  dbname: "bastion"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600 # 秒

# Redis配置
redis:
  host: "172.20.0.8"  # Redis容器的固定IP
  port: 6379
  password: ""
  db: 0
  poolSize: 100
  minIdleConns: 10

# JWT配置
jwt:
  secret: "bastion-jwt-secret-docker-2025"
  expire: 86400 # 24小时，单位秒
  issuer: "bastion"

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    path: "./logs/app.log"
    maxSize: 100    # MB
    maxBackups: 10
    maxAge: 30      # 天
    compress: true

# SSH配置
ssh:
  timeout: 30     # 连接超时时间，秒
  keepalive: 60   # 心跳间隔，秒
  maxSessions: 100 # 最大并发会话数

# 会话配置
session:
  timeout: 3600   # 会话超时时间，秒
  recordPath: "./recordings" # 会话录制文件路径
  enableRecord: true # 是否启用会话录制

# 安全配置
security:
  enableRateLimit: true
  rateLimit:
    requests: 100   # 每分钟请求数限制
    burst: 10       # 突发请求数
  cors:
    # 生产环境：添加您的实际域名和IP
    # 示例配置包含了常见的访问方式
    allowOrigins: [
      "http://localhost:8080",
      "http://127.0.0.1:8080",
      "http://172.20.0.5",
      "http://47.115.133.178:8080",  # 您的公网IP
      "https://47.115.133.178",       # HTTPS访问
      # 如果有域名，添加在这里
      # "https://your-domain.com",
      # "https://www.your-domain.com"
    ]
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowHeaders: ["Content-Type", "Authorization", "Origin", "X-Requested-With"]
    exposeHeaders: ["Content-Length", "Content-Type"]
    allowCredentials: true
    maxAge: 3600

# 文件上传配置
upload:
  maxSize: 10     # MB
  allowTypes: [".jpg", ".png", ".gif", ".pdf", ".txt"]
  savePath: "./uploads"

# 监控配置
monitoring:
  enableMetrics: true
  metricsPath: "/metrics"
  enableHealth: true
  healthPath: "/api/v1/health"

# 通知配置
notification:
  email:
    smtp:
      host: ""
      port: 587
      username: ""
      password: ""
    from: ""
  webhook:
    url: ""
    timeout: 10

# 审计配置
audit:
  enableOperationLog: true
  enableSessionRecord: true
  retentionDays: 30    # 生产环境保留30天
  dangerousCommands:
    - "rm -rf"
    - "mkfs"
    - "dd if="
    - "iptables -F"
    - "shutdown"
    - "reboot"
    - "passwd"
    - "userdel"