version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: bastion-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: bastion
      MYSQL_USER: bastion
      MYSQL_PASSWORD: bastion123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - bastion-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: bastion-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - bastion-network

  # 后端服务 (开发环境下手动启动)
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   container_name: bastion-backend
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #     - ./logs:/app/logs
  #   environment:
  #     - GIN_MODE=debug
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_USER=bastion
  #     - DB_PASSWORD=bastion123
  #     - DB_NAME=bastion
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   depends_on:
  #     - mysql
  #     - redis
  #   networks:
  #     - bastion-network

  # 前端服务 (开发环境下手动启动)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: bastion-frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080
  #   depends_on:
  #     - backend
  #   networks:
  #     - bastion-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  bastion-network:
    driver: bridge 